image: docker:18.09.7
services:
  - docker:17-dind

stages:
  - build

variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  CONTAINER_IMAGE_OPENRESTY: $CI_REGISTRY/$CI_PROJECT_PATH/nginx-openresty
  CONTAINER_IMAGE_WEBAPP: $CI_REGISTRY/$CI_PROJECT_PATH/webapp
  DOCKER_DRIVER: overlay

build_openresty:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE_OPENRESTY:latest || true
    - docker build --cache-from $CONTAINER_IMAGE_OPENRESTY:latest -t $CONTAINER_IMAGE_OPENRESTY:$CI_BUILD_REF -t $CONTAINER_IMAGE_OPENRESTY:latest ./nginx-image
    - docker push $CONTAINER_IMAGE_OPENRESTY:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE_OPENRESTY:latest
    - echo $CONTAINER_IMAGE_OPENRESTY:$CI_BUILD_REF

# build_webapp:
#   stage: build
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker pull $CONTAINER_IMAGE_WEBAPP:latest || true
#     - docker build --cache-from $CONTAINER_IMAGE_WEBAPP:latest -t $CONTAINER_IMAGE_WEBAPP:$CI_BUILD_REF -t $CONTAINER_IMAGE_WEBAPP:latest ./webapp
#     - docker push $CONTAINER_IMAGE_WEBAPP:$CI_BUILD_REF
#     - docker push $CONTAINER_IMAGE_WEBAPP:latest
#     - echo $CONTAINER_IMAGE_WEBAPP:$CI_BUILD_REF

